### ISSUE TITLE
Soundcloud remote works only with active soundcloud browser tab

### ISSUE THREAD

**Issue by may-tau** [unifiedremote/Remotes#104]
Whenever I switch to another tab or minimize the browser the remote stops working properly . Obviously it sends some commands into current context - on the desktop it selects/deselects shortcut icons; in other browser tabs it scrolls the page.

Is it possible to "smartify" the remote to "search" for soundcloud in opened browser/tabs and send the commands there?

**Comment by pqvst** [comment]
Unfortunately the browser remotes require the tab to be active.
