### ISSUE TITLE
iTunes remote shows no content. 

### ISSUE THREAD

**Issue by jtheletter** [unifiedremote/Remotes#115]
The "Player" section of the iTunes remote says "Not Available", and the "Playlist" section is empty. 

The "Playback section" shows controls like volume, stop, and these seem to work. 

"iTunes Preferences / Share iTunes Library XML with other applications" is enabled. 

"System Preferences / Security & Privacy / Privacy / Accessibility" for Unified Remote is enabled. 

macOS 10.14.4 "Mojave"

iOS 12.2

**Comment by pqvst** [comment]
Tested with Mojave and iOS. Cannot reproduce issue.

**Comment by jtheletter** [comment]
Tested today with Mojave 10.14.6, iTunes Version 12.9.5.5, iOS 12.3.1, and yes, issue seems resolved, thanks.
