### ISSUE TITLE
Custom remotes dident show up

### ISSUE THREAD

**Issue by linonetwo** [unifiedremote/Remotes#119]
I tried `Pixel` and `Spy`, puted into `~/Library/Application Support/Unified Remote/Remotes/Custom` and click restart server, they didn't show up in the `http://localhost:9510/web/#/remotes` and the android.

**Comment by linonetwo** [comment]
I tried to add `/Users/xxx/Library/Application Support/Unified Remote/Remotes/Custom/` to `http://localhost:9510/web/#/settings/remotes` but still not working.

**Comment by pqvst** [comment]
Pixel and Spy remotes will not work on Mac, those are windows specific remotes.
