### ISSUE TITLE
Chrome Remote

### ISSUE THREAD

**Issue by galeamark7** [unifiedremote/Remotes#12]
Issue in remote.lua for chrome remote
On windows 7 64-bit this code does not identify the chrome window

actions.switch = function()
	if OS_WINDOWS then
		local hwnd = win.window("chrome.exe");
		if (hwnd == 0) then actions.launch(); end
		win.switchtowait("chrome.exe");
	end
end

A new chrome window is launched when any button is pressed, also the commands are passed to the focused window rather than the chrome windows. I Think it is because chrome.exe is running multiple instances. I have been unable to find a work around.

**Comment by ui-philip** [comment]
I'm running Windows 7 64-bit and not experiencing any issues with the Chrome remote. What version of Chrome are you using?

**Comment by galeamark7** [comment]
hi After Force closing several of the chrome.exe from task manager, Remote started working. after logon, sometimes it works, sometimes it doesn't, but my guess is that somehow an extension is interfering or the wrong chrome.exe is put into focus. I solved the problem by creating a custom remote that does not check if chrome is in focus. I just focus on chrome manually with Ctrl+Alt+Del before using remote, it is good enough for me.

**Comment by galeamark7** [comment]
I also wanted to inform you that the kodi keyboard remote.lua has some errors wich i solved,
play pause is the space key not "P"
mute should be F8
vol- should be F9
vol+ should be F10
