### ISSUE TITLE
Can I switch remote based on currently activated window?

### ISSUE THREAD

**Issue by linonetwo** [unifiedremote/Remotes#134]
So I can achieve something like Mac's multi touch bar, which is context aware.

Is there an API to do so?

**Comment by pqvst** [comment]
There is no built-in support for this at the moment.

If you want to switch between custom remotes then you could probably achieve this by running a shell script or apple script to fetch the current active window and then switch remote.

Script library:
https://github.com/unifiedremote/Docs/blob/master/libs/script.md

Switch remote:
https://github.com/unifiedremote/Docs/blob/master/libs/device.md#deviceswitch-id-
