### ISSUE TITLE
Stremio Remote not showing

### ISSUE THREAD

**Issue by kooolarpan** [unifiedremote/Remotes#142]
![Screenshot_2020-05-26-19-37-54-153_com Relmtech Remote](https://user-images.githubusercontent.com/33162706/82909039-783f3b80-9f88-11ea-969b-cc135760d81f.jpg)

**Comment by jaruba** [comment]
I made that remote, and I don't see it either.

@pqvst what happened to it?

**Comment by pqvst** [comment]
Sorry, the release got delayed. New server build coming soon

**Comment by kooolarpan** [comment]
I have found that Unified Remote Pro Version has that Stremio Remote not on
the regular version.
