### ISSUE TITLE
_Still_ no way to view other monitors?

### ISSUE THREAD

**Issue by turkeyphant** [unifiedremote/Remotes#143]
When is this due to be implemented?

**Comment by wozhdal** [comment]
yes, need it !! :)

**Comment by pqvst** [comment]
The latest version of the server supports multiple monitors. Download it here:
https://www.unifiedremote.com/

**Comment by turkeyphant** [comment]
> The latest version of the server supports multiple monitors. Download it here:
> https://www.unifiedremote.com/

Using latest version from website (3.10.0.2467 (49)) there still doesn't seem to be a way to view other monitors.

**Comment by pqvst** [comment]
> > The latest version of the server supports multiple monitors. Download it here:
> > https://www.unifiedremote.com/
> 
> Using latest version from website (3.10.0.2467 (49)) there still doesn't seem to be a way to view other monitors.

If the server detects multiple monitors there should be a choice inside the Screen remote to change monitor. What OS are you running on your computer?

**Comment by turkeyphant** [comment]
Windows 10. No buttons on Screen remote, just shows monitor 1 and nothing else.
