### ISSUE TITLE
"Windows Service" no longer present?

### ISSUE THREAD

**Issue by wergio** [unifiedremote/Remotes#156]
in the latest server version I cannot find anymore the "Windows Service" experimental feature. And so keyboard is not working on login screen before first login

**Comment by pqvst** [comment]
Yes, we have temporarily removed the "Windows Service" feature due to compatibility issues. However, you can still grab the older server version using this link:
https://www.unifiedremote.com/static/builds/server/windows-x86/2463/ServerSetup-3.9.0.2463.exe
