### ISSUE TITLE
Netflix remote for Linux missing 2 buttons

### ISSUE THREAD

**Issue by lauperezm** [unifiedremote/Remotes#50]
This user reported a problem with missing buttons in the Netflix remote for Linux: https://unifiedremote.zendesk.com/agent/tickets/4677  

The cause is a problem in the Linux code for this remote. This thread found a solution for it that needs to be added to the server: http://community.unifiedremote.com/topic/405/where-is-the-fullscreen-ur-button-for-netflix/3

**Comment by pqvst** [comment]
Fixed in server 3.3.5
