### ISSUE TITLE
Google Music remote - Volume down button not working

### ISSUE THREAD

**Issue by lauperezm** [unifiedremote/Remotes#52]
Issue reported by user, ticket 4872: https://unifiedremote.zendesk.com/agent/tickets/4872 

Server version: 3.3.4.889 (39)

OS: Windows 10 x 64

Platform: Windows NT 6.2 (Build 9200) IA32

Image of the button not working: https://unifiedremote.zendesk.com/attachments/token/wh3HyAHRAVvYS67ShG1UoJQvU/?name=01.PNG

**Comment by pqvst** [comment]
Fixed in iOS version 1.4.3
