### ISSUE TITLE
VLC Advanced remote bugs

### ISSUE THREAD

**Issue by lauperezm** [unifiedremote/Remotes#74]
User reports two problems: 
1. Not possible to change the position of the currently playing track using the UI: this issue was replicated at the office. 
2. Not possible to access the playlist: this needs to be confirmed

Ticket: https://unifiedremote.zendesk.com/agent/tickets/6074

**Comment by pqvst** [comment]
1. Couldn't reproduce. Changing position works as expected.
2. Playlist works as expected.
