### ISSUE TITLE
Plex Home Theater error - Mac

### ISSUE THREAD

**Issue by lauperezm** [unifiedremote/Remotes#80]
User reports that the "Menu" button in the Plex Home Theater Remote is missing a functionality. When using a Logitech Harmony Universal Remote, clicking on the "Menu" button when in the "Guide" view of listed content pulls up new actions. This is not the case with the remote's button. 

Ticket includes a screenshot of the menu that is missing: https://unifiedremote.zendesk.com/agent/tickets/6201

**Comment by pqvst** [comment]
I can't even find Plex Home Theater for mac...
